[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File /fluent-bit/etc/parsers.conf

[INPUT]
    Name           tail
    Path           /var/log/host/syslog
    Tag            system.syslog
    Parser         syslog-rfc3164

[OUTPUT]
    Name            es
    Match           *
    Host            elasticsearch
    Port            9200
    Index           system-logs
    Suppress_type_name   On
